[package]
name = "wooting_visualizer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.11.0"
wooting-sdk = "0.1.0"
rand = "0.7.3"